# Generated by ariadne-codegen
# Source: stash_vroom/queries.graphql

from typing import Any, Dict, List, Optional, Union

from .base_client import BaseClient
from .base_model import UNSET, UnsetType
from .configuration import Configuration
from .enums import FilterMode
from .images_by_ids import ImagesByIds
from .images_by_search import ImagesBySearch
from .images_by_tag_ids import ImagesByTagIds
from .input_types import FindFilterType, SceneFilterType
from .save_config import SaveConfig
from .saved_filters import SavedFilters
from .scene_ids import SceneIds
from .scenes import Scenes
from .tags_by_regex import TagsByRegex
from .version import Version


def gql(q: str) -> str:
    return q


class Stash(BaseClient):
    def version(self, **kwargs: Any) -> Version:
        query = gql(
            """
            query Version {
              version {
                hash
                version
                build_time
              }
            }
            """
        )
        variables: Dict[str, object] = {}
        response = self.execute(
            query=query, operation_name="Version", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return Version.model_validate(data)

    def configuration(self, **kwargs: Any) -> Configuration:
        query = gql(
            """
            query Configuration {
              configuration {
                general {
                  ffmpegPath
                  ffprobePath
                  parallelTasks
                  stashBoxes {
                    name
                    endpoint
                    api_key
                  }
                }
                plugins
              }
            }
            """
        )
        variables: Dict[str, object] = {}
        response = self.execute(
            query=query, operation_name="Configuration", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return Configuration.model_validate(data)

    def save_config(self, plugin_id: str, input: Any, **kwargs: Any) -> SaveConfig:
        query = gql(
            """
            mutation SaveConfig($plugin_id: ID!, $input: Map!) {
              configurePlugin(plugin_id: $plugin_id, input: $input)
            }
            """
        )
        variables: Dict[str, object] = {"plugin_id": plugin_id, "input": input}
        response = self.execute(
            query=query, operation_name="SaveConfig", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return SaveConfig.model_validate(data)

    def saved_filters(self, mode: FilterMode, **kwargs: Any) -> SavedFilters:
        query = gql(
            """
            query SavedFilters($mode: FilterMode!) {
              findSavedFilters(mode: $mode) {
                ...SavedFilterData
              }
            }

            fragment SavedFilterData on SavedFilter {
              id
              mode
              name
              find_filter {
                q
                page
                per_page
                sort
                direction
              }
              object_filter
              ui_options
            }
            """
        )
        variables: Dict[str, object] = {"mode": mode}
        response = self.execute(
            query=query, operation_name="SavedFilters", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return SavedFilters.model_validate(data)

    def scenes(
        self, find_filter: FindFilterType, scene_filter: SceneFilterType, **kwargs: Any
    ) -> Scenes:
        query = gql(
            """
            query Scenes($find_filter: FindFilterType!, $scene_filter: SceneFilterType!) {
              findScenes(filter: $find_filter, scene_filter: $scene_filter) {
                count
                duration
                filesize
                scenes {
                  ...Scene
                }
              }
            }

            fragment Scene on Scene {
              id
              urls
              title
              details
              rating100
              date
              created_at
              o_counter
              play_count
              studio {
                name
                tags {
                  id
                  name
                }
                parent_studio {
                  name
                  parent_studio {
                    name
                    parent_studio {
                      name
                    }
                  }
                }
              }
              paths {
                stream
                screenshot
                preview
              }
              files {
                format
                basename
                size
                width
                height
                duration
                fingerprints {
                  type
                  value
                }
              }
              performers {
                id
                name
                gender
                country
                favorite
                ethnicity
                fake_tits
                tags {
                  name
                }
              }
              scene_markers {
                id
                seconds
                primary_tag {
                  name
                }
                tags {
                  id
                  name
                  parents {
                    id
                    name
                    parents {
                      id
                      name
                      parents {
                        id
                        name
                      }
                    }
                  }
                }
              }
              tags {
                id
                name
                parents {
                  id
                  name
                  parents {
                    id
                    name
                    parents {
                      id
                      name
                    }
                  }
                }
              }
            }
            """
        )
        variables: Dict[str, object] = {
            "find_filter": find_filter,
            "scene_filter": scene_filter,
        }
        response = self.execute(
            query=query, operation_name="Scenes", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return Scenes.model_validate(data)

    def scene_ids(
        self, find_filter: FindFilterType, scene_filter: SceneFilterType, **kwargs: Any
    ) -> SceneIds:
        query = gql(
            """
            query SceneIds($find_filter: FindFilterType!, $scene_filter: SceneFilterType!) {
              findScenes(filter: $find_filter, scene_filter: $scene_filter) {
                count
                duration
                filesize
                scenes {
                  id
                }
              }
            }
            """
        )
        variables: Dict[str, object] = {
            "find_filter": find_filter,
            "scene_filter": scene_filter,
        }
        response = self.execute(
            query=query, operation_name="SceneIds", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return SceneIds.model_validate(data)

    def images_by_ids(
        self, ids: Union[Optional[List[str]], UnsetType] = UNSET, **kwargs: Any
    ) -> ImagesByIds:
        query = gql(
            """
            query ImagesByIds($ids: [ID!]) {
              findImages(ids: $ids, filter: {per_page: -1}) {
                images {
                  ...Img
                }
              }
            }

            fragment Img on Image {
              id
              urls
              title
              paths {
                image
                thumbnail
                preview
              }
              tags {
                id
                name
              }
              visual_files {
                __typename
                ... on ImageFile {
                  id
                  path
                  size
                  width
                  height
                  fingerprints {
                    type
                    value
                  }
                }
              }
            }
            """
        )
        variables: Dict[str, object] = {"ids": ids}
        response = self.execute(
            query=query, operation_name="ImagesByIds", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return ImagesByIds.model_validate(data)

    def images_by_search(self, q: str, **kwargs: Any) -> ImagesBySearch:
        query = gql(
            """
            query ImagesBySearch($q: String!) {
              findImages(ids: [], filter: {q: $q, per_page: -1}) {
                images {
                  ...Img
                }
              }
            }

            fragment Img on Image {
              id
              urls
              title
              paths {
                image
                thumbnail
                preview
              }
              tags {
                id
                name
              }
              visual_files {
                __typename
                ... on ImageFile {
                  id
                  path
                  size
                  width
                  height
                  fingerprints {
                    type
                    value
                  }
                }
              }
            }
            """
        )
        variables: Dict[str, object] = {"q": q}
        response = self.execute(
            query=query, operation_name="ImagesBySearch", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return ImagesBySearch.model_validate(data)

    def images_by_tag_ids(
        self, ids: Union[Optional[List[str]], UnsetType] = UNSET, **kwargs: Any
    ) -> ImagesByTagIds:
        query = gql(
            """
            query ImagesByTagIds($ids: [ID!]) {
              findImages(image_filter: {tags: {modifier: INCLUDES, value: $ids}}) {
                images {
                  ...Img
                }
              }
            }

            fragment Img on Image {
              id
              urls
              title
              paths {
                image
                thumbnail
                preview
              }
              tags {
                id
                name
              }
              visual_files {
                __typename
                ... on ImageFile {
                  id
                  path
                  size
                  width
                  height
                  fingerprints {
                    type
                    value
                  }
                }
              }
            }
            """
        )
        variables: Dict[str, object] = {"ids": ids}
        response = self.execute(
            query=query, operation_name="ImagesByTagIds", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return ImagesByTagIds.model_validate(data)

    def tags_by_regex(self, regex: str, **kwargs: Any) -> TagsByRegex:
        query = gql(
            """
            query TagsByRegex($regex: String!) {
              findTags(
                tag_filter: {name: {value: $regex, modifier: MATCHES_REGEX}}
                filter: {per_page: -1}
              ) {
                tags {
                  id
                  name
                }
              }
            }
            """
        )
        variables: Dict[str, object] = {"regex": regex}
        response = self.execute(
            query=query, operation_name="TagsByRegex", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return TagsByRegex.model_validate(data)
