# Generated by ariadne-codegen
# Source: stash_vroom/queries.graphql

from typing import List

from .base_model import BaseModel


class Configuration(BaseModel):
    configuration: "ConfigurationConfiguration"


class ConfigurationConfiguration(BaseModel):
    general: "ConfigurationConfigurationGeneral"


class ConfigurationConfigurationGeneral(BaseModel):
    ffmpegPath: str
    ffprobePath: str
    stashBoxes: List["ConfigurationConfigurationGeneralStashBoxes"]


class ConfigurationConfigurationGeneralStashBoxes(BaseModel):
    name: str
    endpoint: str
    api_key: str


Configuration.model_rebuild()
ConfigurationConfiguration.model_rebuild()
ConfigurationConfigurationGeneral.model_rebuild()
