# Generated by ariadne-codegen
# Source: http://localhost:9999/graphql

from enum import Enum


class BlobsStorageType(str, Enum):
    DATABASE = "DATABASE"
    FILESYSTEM = "FILESYSTEM"


class BulkUpdateIdMode(str, Enum):
    SET = "SET"
    ADD = "ADD"
    REMOVE = "REMOVE"


class CircumisedEnum(str, Enum):
    CUT = "CUT"
    UNCUT = "UNCUT"


class CriterionModifier(str, Enum):
    EQUALS = "EQUALS"
    NOT_EQUALS = "NOT_EQUALS"
    GREATER_THAN = "GREATER_THAN"
    LESS_THAN = "LESS_THAN"
    IS_NULL = "IS_NULL"
    NOT_NULL = "NOT_NULL"
    INCLUDES_ALL = "INCLUDES_ALL"
    INCLUDES = "INCLUDES"
    EXCLUDES = "EXCLUDES"
    MATCHES_REGEX = "MATCHES_REGEX"
    NOT_MATCHES_REGEX = "NOT_MATCHES_REGEX"
    BETWEEN = "BETWEEN"
    NOT_BETWEEN = "NOT_BETWEEN"


class FilterMode(str, Enum):
    SCENES = "SCENES"
    PERFORMERS = "PERFORMERS"
    STUDIOS = "STUDIOS"
    GALLERIES = "GALLERIES"
    SCENE_MARKERS = "SCENE_MARKERS"
    MOVIES = "MOVIES"
    GROUPS = "GROUPS"
    TAGS = "TAGS"
    IMAGES = "IMAGES"


class GenderEnum(str, Enum):
    MALE = "MALE"
    FEMALE = "FEMALE"
    TRANSGENDER_MALE = "TRANSGENDER_MALE"
    TRANSGENDER_FEMALE = "TRANSGENDER_FEMALE"
    INTERSEX = "INTERSEX"
    NON_BINARY = "NON_BINARY"


class HashAlgorithm(str, Enum):
    MD5 = "MD5"
    OSHASH = "OSHASH"


class IdentifyFieldStrategy(str, Enum):
    IGNORE = "IGNORE"
    MERGE = "MERGE"
    OVERWRITE = "OVERWRITE"


class ImageLightboxDisplayMode(str, Enum):
    ORIGINAL = "ORIGINAL"
    FIT_XY = "FIT_XY"
    FIT_X = "FIT_X"


class ImageLightboxScrollMode(str, Enum):
    ZOOM = "ZOOM"
    PAN_Y = "PAN_Y"


class ImportDuplicateEnum(str, Enum):
    IGNORE = "IGNORE"
    OVERWRITE = "OVERWRITE"
    FAIL = "FAIL"


class ImportMissingRefEnum(str, Enum):
    IGNORE = "IGNORE"
    FAIL = "FAIL"
    CREATE = "CREATE"


class JobStatus(str, Enum):
    READY = "READY"
    RUNNING = "RUNNING"
    FINISHED = "FINISHED"
    STOPPING = "STOPPING"
    CANCELLED = "CANCELLED"
    FAILED = "FAILED"


class JobStatusUpdateType(str, Enum):
    ADD = "ADD"
    REMOVE = "REMOVE"
    UPDATE = "UPDATE"


class LogLevel(str, Enum):
    Trace = "Trace"
    Debug = "Debug"
    Info = "Info"
    Progress = "Progress"
    Warning = "Warning"
    Error = "Error"


class OrientationEnum(str, Enum):
    LANDSCAPE = "LANDSCAPE"
    PORTRAIT = "PORTRAIT"
    SQUARE = "SQUARE"


class PackageType(str, Enum):
    Scraper = "Scraper"
    Plugin = "Plugin"


class PluginSettingTypeEnum(str, Enum):
    STRING = "STRING"
    NUMBER = "NUMBER"
    BOOLEAN = "BOOLEAN"


class PreviewPreset(str, Enum):
    ultrafast = "ultrafast"
    veryfast = "veryfast"
    fast = "fast"
    medium = "medium"
    slow = "slow"
    slower = "slower"
    veryslow = "veryslow"


class ResolutionEnum(str, Enum):
    VERY_LOW = "VERY_LOW"
    LOW = "LOW"
    R360P = "R360P"
    STANDARD = "STANDARD"
    WEB_HD = "WEB_HD"
    STANDARD_HD = "STANDARD_HD"
    FULL_HD = "FULL_HD"
    QUAD_HD = "QUAD_HD"
    VR_HD = "VR_HD"
    FOUR_K = "FOUR_K"
    FIVE_K = "FIVE_K"
    SIX_K = "SIX_K"
    SEVEN_K = "SEVEN_K"
    EIGHT_K = "EIGHT_K"
    HUGE = "HUGE"


class ScrapeContentType(str, Enum):
    GALLERY = "GALLERY"
    IMAGE = "IMAGE"
    MOVIE = "MOVIE"
    GROUP = "GROUP"
    PERFORMER = "PERFORMER"
    SCENE = "SCENE"


class ScrapeType(str, Enum):
    NAME = "NAME"
    FRAGMENT = "FRAGMENT"
    URL = "URL"


class SortDirectionEnum(str, Enum):
    ASC = "ASC"
    DESC = "DESC"


class StreamingResolutionEnum(str, Enum):
    LOW = "LOW"
    STANDARD = "STANDARD"
    STANDARD_HD = "STANDARD_HD"
    FULL_HD = "FULL_HD"
    FOUR_K = "FOUR_K"
    ORIGINAL = "ORIGINAL"


class SystemStatusEnum(str, Enum):
    SETUP = "SETUP"
    NEEDS_MIGRATION = "NEEDS_MIGRATION"
    OK = "OK"
