# Generated by ariadne-codegen
# Source: stash_vroom/queries.graphql

from typing import List

from .base_model import BaseModel
from .fragments import Img


class ImagesBySearch(BaseModel):
    findImages: "ImagesBySearchFindImages"


class ImagesBySearchFindImages(BaseModel):
    images: List["ImagesBySearchFindImagesImages"]


class ImagesBySearchFindImagesImages(Img):
    pass


ImagesBySearch.model_rebuild()
ImagesBySearchFindImages.model_rebuild()
