# Generated by ariadne-codegen
# Source: stash_vroom/queries.graphql

from typing import List

from .base_model import BaseModel
from .fragments import Img


class ImagesByTagIds(BaseModel):
    findImages: "ImagesByTagIdsFindImages"


class ImagesByTagIdsFindImages(BaseModel):
    images: List["ImagesByTagIdsFindImagesImages"]


class ImagesByTagIdsFindImagesImages(Img):
    pass


ImagesByTagIds.model_rebuild()
ImagesByTagIdsFindImages.model_rebuild()
