# Generated by ariadne-codegen
# Source: stash_vroom/queries.graphql

from typing import List

from .base_model import BaseModel
from .fragments import Img


class ImagesByIds(BaseModel):
    findImages: "ImagesByIdsFindImages"


class ImagesByIdsFindImages(BaseModel):
    images: List["ImagesByIdsFindImagesImages"]


class ImagesByIdsFindImagesImages(Img):
    pass


ImagesByIds.model_rebuild()
ImagesByIdsFindImages.model_rebuild()
