# Generated by ariadne-codegen
# Source: stash_vroom/queries.graphql

from typing import List

from .base_model import BaseModel
from .fragments import SavedFilterData


class SavedFilters(BaseModel):
    findSavedFilters: List["SavedFiltersFindSavedFilters"]


class SavedFiltersFindSavedFilters(SavedFilterData):
    pass


SavedFilters.model_rebuild()
