# Generated by ariadne-codegen
# Source: stash_vroom/queries.graphql

from typing import List

from .base_model import BaseModel
from .fragments import Scene


class Scenes(BaseModel):
    findScenes: "ScenesFindScenes"


class ScenesFindScenes(BaseModel):
    count: int
    duration: float
    filesize: float
    scenes: List["ScenesFindScenesScenes"]


class ScenesFindScenesScenes(Scene):
    pass


Scenes.model_rebuild()
ScenesFindScenes.model_rebuild()
