# Generated by ariadne-codegen
# Source: stash_vroom/queries.graphql

from typing import List

from .base_model import BaseModel


class SceneIds(BaseModel):
    findScenes: "SceneIdsFindScenes"


class SceneIdsFindScenes(BaseModel):
    count: int
    duration: float
    filesize: float
    scenes: List["SceneIdsFindScenesScenes"]


class SceneIdsFindScenesScenes(BaseModel):
    id: str


SceneIds.model_rebuild()
SceneIdsFindScenes.model_rebuild()
