# Generated by ariadne-codegen
# Source: stash_vroom/queries.graphql

from typing import List

from .base_model import BaseModel


class StashBoxes(BaseModel):
    configuration: "StashBoxesConfiguration"


class StashBoxesConfiguration(BaseModel):
    general: "StashBoxesConfigurationGeneral"


class StashBoxesConfigurationGeneral(BaseModel):
    stashBoxes: List["StashBoxesConfigurationGeneralStashBoxes"]


class StashBoxesConfigurationGeneralStashBoxes(BaseModel):
    name: str
    endpoint: str
    api_key: str


StashBoxes.model_rebuild()
StashBoxesConfiguration.model_rebuild()
StashBoxesConfigurationGeneral.model_rebuild()
