# Generated by ariadne-codegen
# Source: stash_vroom/queries.graphql

from typing import List

from .base_model import BaseModel


class TagsByRegex(BaseModel):
    findTags: "TagsByRegexFindTags"


class TagsByRegexFindTags(BaseModel):
    tags: List["TagsByRegexFindTagsTags"]


class TagsByRegexFindTagsTags(BaseModel):
    id: str
    name: str


TagsByRegex.model_rebuild()
TagsByRegexFindTags.model_rebuild()
