# Generated by ariadne-codegen
# Source: stash_vroom/queries.graphql

from typing import Optional

from .base_model import BaseModel


class Version(BaseModel):
    version: "VersionVersion"


class VersionVersion(BaseModel):
    hash: str
    version: Optional[str]
    build_time: str


Version.model_rebuild()
